#! /usr/bin/python3

from sys import argv
from os import system

def main():
    with open(argv[1], 'r') as f:
        for line in f:
            text = line.strip()
            print(text)
            system('sam-say "' + text + '"')

main()

